# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ojal board-specific Kconfig settings.

CONFIG_BOARD_OJAL=y

# eSPI
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

#Disable Power Delivery Function
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
CONFIG_PLATFORM_EC_USBC_SS_MUX=n
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_USB_MUX_TASK=n
CONFIG_PLATFORM_EC_USB_PD_REQUIRE_AP_MODE_ENTRY=n
CONFIG_PLATFORM_EC_USB_PD_TBT_COMPAT_MODE=n
CONFIG_PLATFORM_EC_USB_PD_USB4=n
CONFIG_PLATFORM_EC_USB_PD_DP_MODE=y
CONFIG_PLATFORM_EC_USB_PD_HOST_CMD=y
CONFIG_PLATFORM_EC_USB_PD_REV30=y
CONFIG_PLATFORM_EC_USBC=y

# PDC
CONFIG_PLATFORM_EC_USB_PD_CONTROLLER=y
CONFIG_PDC_RUNTIME_PORT_CONFIG=n
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_RAA489110=n
CONFIG_PLATFORM_EC_CHARGER_ISL9238C=y
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=10
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=20
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_PDC=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n

# Battery support
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y

# Keyboard support
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_PLATFORM_EC_KEYBOARD=y
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# User input
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Disable options not yet configured
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
