# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ojal board-specific Kconfig settings.

CONFIG_BOARD_OJAL=y

# eSPI
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

# Disable options not yet configured
CONFIG_NAMED_ADC_CHANNELS=n
CONFIG_PWM=n
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_PLATFORM_EC_I2C=n
CONFIG_PLATFORM_EC_BUTTON=n
CONFIG_UCSI_PPM=n
CONFIG_PLATFORM_EC_MKBP_EVENT=n
CONFIG_PLATFORM_EC_MKBP_INPUT_DEVICES=n
CONFIG_PLATFORM_EC_MKBP_USE_GPIO_AND_HOST_EVENT=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
