# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CPP=y
CONFIG_STD_CPP20=y # coreboot g++ __cplusplus 201703L
CONFIG_REQUIRES_FULL_LIBCPP=y

CONFIG_NANOPB=y

# Pigweed
CONFIG_PIGWEED_ASSERT_ZEPHYR=y
CONFIG_PIGWEED_CHRONO_SYSTEM_CLOCK=y
CONFIG_PIGWEED_SYNC_MUTEX=y

CONFIG_COMMON_LIBC_MALLOC=n

#Common DSP configs between service and client
CONFIG_PLATFORM_EC_DSP_REMOTE_LID_ANGLE=y
CONFIG_PLATFORM_EC_DSP_REMOTE_LID_SWITCH=y
CONFIG_PLATFORM_EC_DSP_REMOTE_TABLET_SWITCH=y
