# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_SYSCON=y

# Shell features
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_KERNEL_SHELL=y

CONFIG_AP=y

# eSPI
CONFIG_ESPI=y
CONFIG_PLATFORM_EC_HOSTCMD=y

# I/O
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y

# Postcode
CONFIG_PLATFORM_EC_PORT80=y
CONFIG_PLATFORM_EC_PORT80_4_BYTE=y

CONFIG_PLATFORM_EC_CBI=y

# FIXME: Features not yet enabled
CONFIG_PLATFORM_EC_SWITCH=n
