# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# quartz board-specific Kconfig settings.

CONFIG_BOARD_QUARTZ=y

CONFIG_GOOGLE_PRIVATE=y

# Fan
CONFIG_PLATFORM_EC_NUM_FANS=2
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=y
CONFIG_PLATFORM_EC_CUSTOM_FAN_DUTY_CONTROL=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# Clock
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=25000000

# Uart
CONFIG_UART_NPCX_USE_MDMA=y

# External Power
CONFIG_PLATFORM_EC_EXTPOWER_GPIO_CUSTOM=y

# Battery
CONFIG_PLATFORM_EC_SMBUS_PEC=y
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10

# CBI
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y

# System Lock
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n
