# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# quartz board-specific Kconfig settings.

CONFIG_BOARD_QUARTZ=y

# Fan
CONFIG_PLATFORM_EC_NUM_FANS=2

# Added as temporary solution to b/437979589
# Issue ec command `apshutdown` before programming EC or AP
CONFIG_PLATFORM_EC_BRINGUP=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
