# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocicat board-specific Kconfig settings.

CONFIG_BOARD_OCICAT=y

# CBI
CONFIG_PLATFORM_EC_CBI=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y

# Disable options by design
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y

# PDC
CONFIG_PDC_RUNTIME_PORT_CONFIG=n
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=20000
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=65000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=3250

# Bring up configs
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y

# Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Charger
CONFIG_PLATFORM_EC_CHARGER_ISL9238=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_8042=y
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=16

# LED
# Config HOOK_TICK interval
CONFIG_CROS_EC_HOOK_TICK_INTERVAL=125000

CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=y

# DSP configs
CONFIG_I2C_TARGET=y
CONFIG_PLATFORM_EC_DSP_SERVICE=y
CONFIG_PLATFORM_EC_DSP_INIT_PRIORITY=80
CONFIG_PLATFORM_EC_DSP_RESPONSE_BUFFER_SIZE=128

CONFIG_PLATFORM_EC_LID_ANGLE=n
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=n

# Fan
CONFIG_PLATFORM_EC_FAN=y
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=y
