# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# atriarvp-rtk board-specific Kconfig settings.

CONFIG_BOARD_ATRIARVP_RTK=y

# This is appropriate for an RVP
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# eSPI
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
# FIXME: This config is not defined for RTS5912 upstream; how does removing this
# break the ESPI shim?
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

# Use GPIO signals for SLP_S3 and SLP_S4 instead of virtual wires
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S3=n
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S4=n

# Dedicated Charge Port
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=y

# Board specific power limits
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=20000
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=100000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=5000
