# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_BAZE=y

# sensor configs
CONFIG_PLATFORM_EC_ACCEL_BMA4XX=y
CONFIG_PLATFORM_EC_LID_ANGLE=y
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=y
CONFIG_PLATFORM_EC_DYNAMIC_MOTION_SENSOR_COUNT=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=y
CONFIG_PLATFORM_EC_KEYBOARD_FACTORY_TEST=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18

# Battery
CONFIG_PLATFORM_EC_BATTERY_INIT_TYPE_RETRY_COUNT=10

# Charger
CONFIG_PLATFORM_EC_CHARGER_INPUT_CURRENT_DERATE_PCT=2

# System lock
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n
