/* -*- mode:c -*-
 *
 * Copyright 2020 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Declare symbolic names for all the GPIOs that we care about.
 * Note: Those with interrupt handlers must be declared first. */

UNIMPLEMENTED(UART1_RX)
UNIMPLEMENTED(PCH_SMI_L)
UNIMPLEMENTED(PCH_SCI_L)
UNIMPLEMENTED(PCH_WAKE_L)
UNIMPLEMENTED(PCH_PLTRST_L)

UNIMPLEMENTED(I2C_A_SCL)
UNIMPLEMENTED(I2C_A_SDA)
UNIMPLEMENTED(I2C_B_SCL)
UNIMPLEMENTED(I2C_B_SDA)
UNIMPLEMENTED(I2C_C_SCL)
UNIMPLEMENTED(I2C_C_SDA)
UNIMPLEMENTED(I2C_E_SCL)
UNIMPLEMENTED(I2C_E_SDA)

UNIMPLEMENTED(POWER_BUTTON_L)
UNIMPLEMENTED(LID_OPEN)
UNIMPLEMENTED(WP_L)

UNIMPLEMENTED(ENTERING_RW)
