# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ANAKIN=y

# sensor configs
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCELGYRO_LSM6DSM=y
CONFIG_PLATFORM_EC_ACCEL_BMA4XX=y
CONFIG_PLATFORM_EC_ACCEL_LIS2DW12=y
CONFIG_PLATFORM_EC_DYNAMIC_MOTION_SENSOR_COUNT=y
CONFIG_PLATFORM_EC_LID_ANGLE=y
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=y
CONFIG_PLATFORM_EC_SENSOR_EC_RATE_FORCE_MODE=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=y
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# battery
CONFIG_PLATFORM_EC_BATTERY_CUTOFF_RETRY_COUNT=10
CONFIG_PLATFORM_EC_BATT_HOST_FULL_FACTOR=99
CONFIG_PLATFORM_EC_CHARGER_PROFILE_OVERRIDE=y
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10
CONFIG_PLATFORM_EC_I2C_VIRTUAL_BATTERY_ADDR=0x0f
CONFIG_PLATFORM_EC_SMART_BATTERY_OPTIONAL_MFG_FUNC=y

# pdc
CONFIG_PDC_POWER_MGMT_SRC_PDO_PEAK_OCP_110=y
CONFIG_PDC_RUNTIME_PORT_CONFIG=y

# usb-c
CONFIG_PLATFORM_EC_USB_PD_3A_PORTS=0
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=15000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=3000
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=45000

# System lock for FW qual
CONFIG_PLATFORM_EC_BRINGUP=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n
CONFIG_USBC_LOG_LEVEL_ERR=y
