# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_EIRTAE=y

CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_SIZE=55296
CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_OFF=2147483648

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y

# VID&PID
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0x507A
