# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelot_mchp board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_MCHP=y
CONFIG_CROS_SYSTEM_XEC=y

CONFIG_MCHP_MEC_UNSIGNED_HEADER=y
CONFIG_MCHP_MEC_HEADER_FLASH_SIZE_256K=y

# For MCHP ESPI Drivers
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y
CONFIG_ESPI_PERIPHERAL_XEC_EMI0=y
CONFIG_ESPI_PERIPHERAL_ACPI_EC_IBF_EVT_DATA=y
CONFIG_ESPI_PERIPHERAL_KBC_OBE_CBK=y
CONFIG_ESPI_PERIPHERAL_KBC_IBF_EVT_DATA=y

# AIC keyboard not supported
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_INPUT=n

# Overwrite the CONFIG_PLATFORM_EC_MKBP_USE_GPIO_AND_HOST_EVENT setting from
# program.conf with host event-only signalling since GPIO_EC_INT_L is not
# available.
CONFIG_PLATFORM_EC_MKBP_USE_HOST_EVENT=y

CONFIG_COMMON_BOARD_ID=y

#Disabled configs as not yet enabled
CONFIG_I2C_TARGET=n
CONFIG_PLATFORM_EC_DSP_SERVICE=n
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=n
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=n
