# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_GROGU=y

# No Motion Sensors
CONFIG_PLATFORM_EC_ACCEL_FIFO=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCELS=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCEL_INFO=n
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=n
CONFIG_PLATFORM_EC_SENSOR_TIGHT_TIMESTAMPS=n
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=n
# Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=n
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=n
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# USB-C
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=45000
CONFIG_PDC_RUNTIME_PORT_CONFIG=y
CONFIG_PDC_POWER_MGMT_SRC_PDO_PEAK_OCP_110=y
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=15001

# System lock
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n

# Battery
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10
