/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H
#define CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H

#ifdef CONFIG_FP_SENSOR_ELAN80
#if defined(CHIP_FAMILY_STM32F4)
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN 15000
#elif defined(CHIP_FAMILY_STM32H7)
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN 40960
#endif
#endif /* CONFIG_FP_SENSOR_ELAN80 */

#ifdef CONFIG_FP_SENSOR_ELAN515
#if defined(CHIP_FAMILY_STM32F4)
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN 15000
#elif defined(CHIP_FAMILY_STM32H7)
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN 67000
#endif
#endif /* CONFIG_FP_SENSOR_ELAN515 */

#define FP_MAX_FINGER_COUNT_ELAN 3

#endif /* CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H */
