/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H
#define CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H

/* Sensor pixel resolution */
#if (defined(CONFIG_FP_SENSOR_ELAN80) || defined(CONFIG_FP_SENSOR_ELAN80SG))
#define FP_ALGORITHM_TEMPLATE_DEPTH_ELAN 15
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN \
	(FP_ALGORITHM_TEMPLATE_DEPTH_ELAN * 1288)
#elif defined(CONFIG_FP_SENSOR_ELAN515)
#define FP_ALGORITHM_TEMPLATE_DEPTH_ELAN 14
#define FP_ALGORITHM_TEMPLATE_SIZE_ELAN \
	(FP_ALGORITHM_TEMPLATE_DEPTH_ELAN * 1288)
#endif

#define FP_MAX_FINGER_COUNT_ELAN 3

#endif /* CROS_EC_DRIVER_FINGERPRINT_ELAN_ELAN_MATCHER_H */
