/* Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Link-specific thermal configuration module for Chrome EC */

#include "thermal.h"
#include "board.h"

struct thermal_config_t thermal_config[TEMP_SENSOR_COUNT] = {
	/* I2C_CPU-Die */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE_ALL}},
	/* I2C_CPU-Object */
	{THERMAL_CONFIG_NO_FLAG, {313, 323, 343, 353, 358}},
	/* I2C_PCH-Die */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE_ALL}},
	/* I2C_PCH-Object */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE,
	 THERMAL_THRESHOLD_DISABLE, 343, THERMAL_THRESHOLD_DISABLE, 358}},
	/* I2C_DDR-Die */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE_ALL}},
	/* I2C_DDR-Object */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE,
	 THERMAL_THRESHOLD_DISABLE, 343, THERMAL_THRESHOLD_DISABLE, 358}},
	/* I2C_Charger-Die */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE_ALL}},
	/* I2C_Charger-Object */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE,
	 THERMAL_THRESHOLD_DISABLE, 343, THERMAL_THRESHOLD_DISABLE, 358}},
	/* ECInternal */
	{THERMAL_CONFIG_NO_FLAG, {THERMAL_THRESHOLD_DISABLE,
	 THERMAL_THRESHOLD_DISABLE, 343, THERMAL_THRESHOLD_DISABLE, 373}},
	/* PECI */
	{THERMAL_CONFIG_WARNING_ON_FAIL,
	 {328, 338, 343, 348, 353}},
};
