# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_SAPPHIRE=y

CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCELGYRO_LSM6DSM=y

# Button
CONFIG_PLATFORM_EC_BUTTON_TRIGGERED_RECOVERY=y

# CBI
CONFIG_PLATFORM_EC_CBI=y

# PDC fw update
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y

# nfc
CONFIG_HAS_TASK_PCHG=y
CONFIG_PLATFORM_EC_CTN730=y
CONFIG_PLATFORM_EC_PERIPHERAL_CHARGER=y

# Detachable
CONFIG_PLATFORM_EC_DETACHABLE_BASE=y
CONFIG_PLATFORM_EC_BASE_ATTACHED_SWITCH=y
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y
