# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_SAPPHIRE=y

CONFIG_GOOGLE_PRIVATE=y

# Sensor
CONFIG_PLATFORM_EC_MAX_SENSOR_FREQ_MILLIHZ=110000
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCELGYRO_LSM6DSM=y

# ADC
CONFIG_ADC_IT8XXX2_VOL_FULL_SCALE=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_CUTOFF_RETRY_COUNT=10
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10
CONFIG_PLATFORM_EC_SMART_BATTERY_OPTIONAL_MFG_FUNC=y

# Button
CONFIG_PLATFORM_EC_BUTTON_TRIGGERED_RECOVERY=y

# CBI
CONFIG_PLATFORM_EC_CBI=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=45000
CONFIG_PLATFORM_EC_CHARGER_PROFILE_OVERRIDE=y

# nfc
CONFIG_HAS_TASK_PCHG=y
CONFIG_PLATFORM_EC_CTN730=y
CONFIG_PLATFORM_EC_PERIPHERAL_CHARGER=y
CONFIG_PLATFORM_EC_WPC_AC_S5_CHARGE=y
CONFIG_PLATFORM_EC_WPC_HALL_ENABLE=y

# Detachable
CONFIG_PLATFORM_EC_DETACHABLE_BASE=y
CONFIG_PLATFORM_EC_BASE_ATTACHED_SWITCH=y
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y
CONFIG_PLATFORM_EC_TABLET_MODE_SKIP_LID_CLOSE=y

# LED
CONFIG_PLATFORM_EC_LED_DT=y

# SPI
CONFIG_SPI_ASYNC=y
CONFIG_SPI=y
CONFIG_SPI_LOG_LEVEL_INF=y

# PDC
CONFIG_USBC_LOG_LEVEL_ERR=y

# Firmware lock
CONFIG_PLATFORM_EC_BRINGUP=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n
