# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_SUNFLOWER=y
CONFIG_AP_X86_INTEL_CUSTOM=y
CONFIG_PLATFORM_EC_POWERSEQ_PP5000_CONTROL=n
# Customized
# Example: sunflower-1.0.1-b2cbb1a
# Need to skip the first 16 characters to get the commit hash
CONFIG_PLATFORM_SIMPLE_VERSION_SHIFT_IDX=16

# Host Interface
CONFIG_PLATFORM_EC_SCI_GPIO=y

# Fan
CONFIG_PLATFORM_EC_NUM_FANS=1
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=n

# Charger
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=10
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=20
CONFIG_PLATFORM_EC_CHARGER_DEFAULT_CURRENT_LIMIT=500
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=15000
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_NOT_PRESENT=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
CONFIG_CHARGER_DYNAMIC_ACOK_REFERENCE=y

# Thermal
CONFIG_PLATFORM_EC_TEMP_SENSOR_F75303=y
CONFIG_PLATFORM_EC_FAN_RPM_CUSTOM=n

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_KEYBOARD_SCANCODE_CALLBACK=y
CONFIG_PLATFORM_EC_IOEX_IT8801=y

# Third party change
CONFIG_THIRD_PARTY_CUSTOMIZED_DESIGN=y

# Project
CONFIG_CHIPSET_INTEL=y
CONFIG_PD_CHIP_CCG6=y
CONFIG_PD_CCG6_WAIT_STABLE_TIMER=415
CONFIG_PD_CCG6_CUSTOMIZE_BATT_MESSAGE=y
CONFIG_SHORT_HIBERNATE_TIMER=7

# PECI
CONFIG_PECI=y

# PS2 mouse emulation
CONFIG_PLATFORM_EC_TOUCHPAD_CUSTOMIZED=y
CONFIG_PLATFORM_EC_8042_AUX=y

# PD
CONFIG_PD_COMMON_VBUS_CONTROL=n
CONFIG_PD_USB_PID=0x001B
CONFIG_PD_CCG6_ERROR_RECOVERY=y
# PD Controllers
# TODO: Once PD controller support is stable we'll want to enable it on future
# platforms
#CONFIG_PLATFORM_EC_CONSOLE_CMD_TYPEC=n
CONFIG_PLATFORM_EC_USBC=n
CONFIG_USB_PDC_POWER_MGMT=n
CONFIG_USB_PD_ALTMODE_INTEL=n

# System
CONFIG_PLATFORM_EC_SYSTEM_JUMP_RW_SUPPORT=y
CONFIG_PLATFORM_EC_POWER_BUTTON_INIT_TIMEOUT=2

# ALS
CONFIG_PLATFORM_EC_DEDICATED_ALS=n
CONFIG_PLATFORM_EC_MOTIONSENSE=y

# Common sensor configs
CONFIG_PLATFORM_EC_ACCEL_FIFO=y
CONFIG_PLATFORM_EC_DYNAMIC_MOTION_SENSOR_COUNT=y
CONFIG_PLATFORM_EC_LID_ANGLE=y
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=y
CONFIG_PLATFORM_EC_SENSOR_TIGHT_TIMESTAMPS=y
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_SENSOR_EC_RATE_FORCE_MODE=y

# Sensor console commands
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCELS=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCEL_INFO=y

# Power button
# The power button is on the outside of the chassis, not covered by the lid
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y
