/* -*- mode:c -*-
 *
 * Copyright 2020 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Declare symbolic names for all the GPIOs that we care about.
 * Note: Those with interrupt handlers must be declared first. */

/* Interrupts */

/* TODO(b/148160415) - Determine correct purpose for these GPIOs */
UNIMPLEMENTED(ENTERING_RW)
UNIMPLEMENTED(WP_L)
UNIMPLEMENTED(QMSPI_CS0)

/* Alternate Mode */
