# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_MTLRVP_M1723=y
CONFIG_PLATFORM_EC_FW_START_OFFSET_IN_EXT_SPI_FLASH=0x4000
CONFIG_PLATFORM_EC_SPI_CLOCK_DIVIDE=3

# TODO: b/486864443 - convert back to a devicetree property.
CONFIG_CROS_SYSTEM_XEC_QSPI_LINES=1

# Flash size reduction (b/488001510)
CONFIG_PWM_SHELL=n
CONFIG_SHELL_TAB=n
