#!/bin/sh
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Meowth configuration
SPIDEV="/dev/spidev1.0"
# Cannonlake PCH GPIOs
GPIOCHIP="gpiochip268"
# GSPI1 ACPI device for FP MCU
SPIID="spi-PRP0001:01"
# FPMCU RST_ODL is on GPP_A23 = 268 + 23 = 291
GPIO_NRST=291
# FPMCU BOOT0 is on GPP_A21 = 268 + 21 = 289
GPIO_BOOT0=289

if [ ! -e "/sys/class/gpio/${GPIOCHIP}" ]
then
	echo "Cannot find the GPIO chip. Are your running on Meowth ?"
	exit 1
fi

if [ ! -f "$1" ]
then
	echo "Invalid image file: $1"
	echo "Usage: $0 ec.bin"
	exit 1
fi

# Remove cros_fp if present
echo "${SPIID}" > /sys/bus/spi/drivers/cros-ec-spi/unbind

# Configure the MCU Boot0 and NRST GPIOs
echo ${GPIO_BOOT0} > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio${GPIO_BOOT0}/direction
echo ${GPIO_NRST} > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio${GPIO_NRST}/direction

# Reset sequence to enter bootloader mode
echo 1 > /sys/class/gpio/gpio${GPIO_BOOT0}/value
echo 0 > /sys/class/gpio/gpio${GPIO_NRST}/value

# load spidev (fail on cros-ec-spi first to change modalias)
echo "${SPIID}" > /sys/bus/spi/drivers/cros-ec-spi/bind
echo "${SPIID}" > /sys/bus/spi/drivers/spidev/bind

# Release reset as the SPI bus is now ready
echo 1 > /sys/class/gpio/gpio${GPIO_NRST}/value

echo "in" > /sys/class/gpio/gpio${GPIO_NRST}/direction

stm32mon -p -s ${SPIDEV} -e -w $1

# unload spidev
echo "${SPIID}" > /sys/bus/spi/drivers/spidev/unbind

# Go back to normal mode
echo "out" > /sys/class/gpio/gpio${GPIO_NRST}/direction
echo 0 > /sys/class/gpio/gpio${GPIO_BOOT0}/value
echo 0 > /sys/class/gpio/gpio${GPIO_NRST}/value
echo 1 > /sys/class/gpio/gpio${GPIO_NRST}/value

# Give up GPIO control
echo "in" > /sys/class/gpio/gpio${GPIO_BOOT0}/direction
echo "in" > /sys/class/gpio/gpio${GPIO_NRST}/direction
echo ${GPIO_BOOT0} > /sys/class/gpio/unexport
echo ${GPIO_NRST} > /sys/class/gpio/unexport

# wait for FP MCU to come back up (including RWSIG delay)
sleep 2
# Put back cros_fp driver
echo "${SPIID}" > /sys/bus/spi/drivers/cros-ec-spi/bind
# Test it
ectool --name=cros_fp version
