# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Extra overrides used by ish projects, use it in the kconfig_files list in
# BUILD.py.

CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_EXTERNAL_LIBCPP=y
CONFIG_LIBGCC_RTLIB=y
