# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Tokenize build
CONFIG_PLATFORM_EC_LOG_TOKENIZED=y
CONFIG_PIGWEED_LOG_TOKENIZED_LIB=y
CONFIG_SHELL_CUSTOM_HEADER=y

# Toolchain options required by the PW tokenizer
CONFIG_CPP=y
CONFIG_COMMON_LIBC_MALLOC=n
CONFIG_COMMON_LIBC_CALLOC=n
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_USE_TOOLCHAIN=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y # coreboot g++ __cplusplus 202002L
