# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_YODA=y
CONFIG_PLATFORM_EC_BRINGUP=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n

CONFIG_PLATFORM_EC_ACCEL_LIS2DW12=y
CONFIG_PLATFORM_EC_LID_ANGLE=y
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=y
CONFIG_PLATFORM_EC_MAX_SENSOR_FREQ_MILLIHZ=125000

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=n
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# PD
CONFIG_PDC_POWER_MGMT_SRC_PDO_PEAK_OCP_110=y
CONFIG_PLATFORM_EC_USB_PD_3A_PORTS_CUSTOM=y
