# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_SYSCON=y

# Shell features
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_KERNEL_SHELL=y
CONFIG_SHELL_CMDS=y

# Bring up configs remove for firmware qual
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# External Power
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y

# Standard shimmed features
CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
CONFIG_PLATFORM_EC_SWITCH=y

# Application processor
CONFIG_AP=y
CONFIG_SPI=y
CONFIG_AP_ARM_QUALCOMM_QC_EXP=y

# Power Sequencing
CONFIG_PLATFORM_EC_POWERSEQ=y
CONFIG_PLATFORM_EC_POWERSEQ_HOST_SLEEP=y
CONFIG_PLATFORM_EC_PMIC_PASSTHRU_POWER_SIGNALS=y
CONFIG_PLATFORM_EC_POWERSEQ_PP5000_CONTROL=n
CONFIG_PLATFORM_EC_HOSTCMD_ENABLE_OFFMODE_HEARTBEAT=y

# ADC config
CONFIG_NAMED_ADC_CHANNELS=y

# PWM
CONFIG_PWM=y

# RTC
CONFIG_PLATFORM_EC_RTC=y
CONFIG_PLATFORM_EC_HOSTCMD_RTC=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_RTC=y

# Battery
CONFIG_PLATFORM_EC_BATTERY=y
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_SMART=y
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y
CONFIG_PLATFORM_EC_BATTERY_CHARGING_OFFLOAD_TO_AP=y
CONFIG_PLATFORM_EC_BATTERY_ACCESS_LIMIT=y

# HostCMD
CONFIG_PLATFORM_EC_HOSTCMD_AP_SHUTDOWN=y
CONFIG_PLATFORM_EC_HOSTCMD_AP_RESET=y

# MKBP event
CONFIG_PLATFORM_EC_MKBP_EVENT=y
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18

# Keyboard
CONFIG_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_SHELL_KBD_MATRIX_STATE=y
CONFIG_CROS_EC_KEYBOARD_INPUT=y
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_MKBP=y
CONFIG_PLATFORM_EC_MKBP_INPUT_DEVICES=y

# EFS2
CONFIG_PLATFORM_EC_VBOOT_EFS2=y

# Enable the I2C Target (Slave) mode API
CONFIG_I2C_TARGET=y

# Disable options not yet configured
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
