# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_PADME=y

# sensor configs
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCELGYRO_LSM6DSM=y
CONFIG_PLATFORM_EC_SENSOR_EC_RATE_FORCE_MODE=y

# battery
CONFIG_PLATFORM_EC_BATT_HOST_FULL_FACTOR=99
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10
CONFIG_PLATFORM_EC_I2C_VIRTUAL_BATTERY_ADDR=0x0f
CONFIG_PLATFORM_EC_SMART_BATTERY_OPTIONAL_MFG_FUNC=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_MKBP=y
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18

# pdc
CONFIG_BOARD_SKYWALKER_SINGLE_USB_TYPEC=y
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=3000
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=45000
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=15000

# Detachable
CONFIG_PLATFORM_EC_DETACHABLE_BASE=y
CONFIG_PLATFORM_EC_BASE_ATTACHED_SWITCH=y

# Uart
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_I2C_TARGET=y
CONFIG_I2C_TARGET_BUFFER_MODE=y
CONFIG_I2C_TARGET_IT8XXX2_MAX_BUF_SIZE=2044
CONFIG_PLATFORM_EC_ONE_WIRE_UART_TABLET=y
