# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-ite board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_ITE=y

CONFIG_COMMON_BOARD_ID=y

# Disable options not yet configured
