# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_OBIWAN=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# No Motion Sensors
CONFIG_PLATFORM_EC_ACCEL_FIFO=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCELS=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCEL_INFO=n
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=n
CONFIG_PLATFORM_EC_SENSOR_TIGHT_TIMESTAMPS=n
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=n

# Battery
CONFIG_PLATFORM_EC_I2C_NACK_RETRY_COUNT=10
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y
CONFIG_PLATFORM_EC_SMART_BATTERY_OPTIONAL_MFG_FUNC=y
CONFIG_PLATFORM_EC_BATTERY_INIT_TYPE_DEFERRED_RETRY_COUNT=20

# Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Charger
CONFIG_PLATFORM_EC_CHARGER_PROFILE_OVERRIDE=y

# pdc
CONFIG_PDC_POWER_MGMT_SRC_PDO_PEAK_OCP_110=y
CONFIG_PLATFORM_EC_USB_PD_3A_PORTS_CUSTOM=y

# System Lock
CONFIG_PLATFORM_EC_BRINGUP=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n
CONFIG_USBC_LOG_LEVEL_ERR=y
