# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Caboc variant Kconfig settings.
CONFIG_BOARD_CABOC=y

# Fan
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_FACTORY_TEST=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# USB-C: PDC
CONFIG_USBC_PDC_TRACE_MSG=y
CONFIG_PDC_POWER_MGMT_SRC_PDO_PEAK_OCP_110=y

# Config HOOK_TICK interval
CONFIG_CROS_EC_HOOK_TICK_INTERVAL=125000
