/* Copyright 2022 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Keyboard configuration */

#ifndef __KEYBOARD_CUSTOMIZATION_H
#define __KEYBOARD_CUSTOMIZATION_H

/*
 * KEYBOARD_COLS_MAX has the build time column size. It's used to allocate
 * exact spaces for arrays. Actual keyboard scanning is done using
 * keyboard_cols, which holds a runtime column size.
 */
#define KEYBOARD_COLS_MAX 16
#define KEYBOARD_ROWS 8

#define DELBIN_KEYBOARD_COL_DOWN 11
#define DELBIN_KEYBOARD_ROW_DOWN 6
#define DELBIN_KEYBOARD_COL_ESC 1
#define DELBIN_KEYBOARD_ROW_ESC 1
#define DELBIN_KEYBOARD_COL_KEY_H 6
#define DELBIN_KEYBOARD_ROW_KEY_H 1
#define DELBIN_KEYBOARD_COL_KEY_R 3
#define DELBIN_KEYBOARD_ROW_KEY_R 7
#define DELBIN_KEYBOARD_COL_LEFT_ALT 10
#define DELBIN_KEYBOARD_ROW_LEFT_ALT 6
#define DELBIN_KEYBOARD_COL_REFRESH 2
#ifdef CONFIG_KEYBOARD_REFRESH_ROW3
#define DELBIN_KEYBOARD_ROW_REFRESH 3
#else
#define DELBIN_KEYBOARD_ROW_REFRESH 2
#endif
#define DELBIN_KEYBOARD_COL_RIGHT_ALT 10
#define DELBIN_KEYBOARD_ROW_RIGHT_ALT 0
#define KEYBOARD_DEFAULT_COL_VOL_UP 4
#define KEYBOARD_DEFAULT_ROW_VOL_UP 0
#define DELBIN_KEYBOARD_COL_LEFT_SHIFT 7
#define DELBIN_KEYBOARD_ROW_LEFT_SHIFT 5

/* Columns for keys we particularly care about */
#define DELBIN_KEYBOARD2_COL_DOWN 11
#define DELBIN_KEYBOARD2_ROW_DOWN 5
#define DELBIN_KEYBOARD2_COL_ESC 1
#define DELBIN_KEYBOARD2_ROW_ESC 1
#define DELBIN_KEYBOARD2_COL_KEY_H 6
#define DELBIN_KEYBOARD2_ROW_KEY_H 1
#define DELBIN_KEYBOARD2_COL_KEY_R 3
#define DELBIN_KEYBOARD2_ROW_KEY_R 7
#define DELBIN_KEYBOARD2_COL_LEFT_ALT 10
#define DELBIN_KEYBOARD2_ROW_LEFT_ALT 6
#define DELBIN_KEYBOARD2_COL_REFRESH 2
#define DELBIN_KEYBOARD2_ROW_REFRESH 3
#define DELBIN_KEYBOARD2_COL_RIGHT_ALT 10
#define DELBIN_KEYBOARD2_ROW_RIGHT_ALT 0
#define DELBIN_KEYBOARD2_COL_LEFT_SHIFT 7
#define DELBIN_KEYBOARD2_ROW_LEFT_SHIFT 1

int keyboard_choose(void);
void key_choose(void);

#endif /* __KEYBOARD_CUSTOMIZATION_H */
