# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_SAKURA=y
CONFIG_PLATFORM_EC_FRAMEWORK_LAPTOP_13=y

# Customized
# Example: sakura-1.0.1-b2cbb1a
# Need to skip the first 13 characters to get the commit hash
CONFIG_PLATFORM_SIMPLE_VERSION_SHIFT_IDX=13

# Charger
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=10
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=20
CONFIG_PLATFORM_EC_CHARGER_DEFAULT_CURRENT_LIMIT=500
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=15000
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_NOT_PRESENT=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y

# Thermal
CONFIG_PLATFORM_EC_TEMP_SENSOR_F75303=y
CONFIG_PLATFORM_EC_TEMP_SENSOR_F75397=y

# Fan
CONFIG_PLATFORM_EC_NUM_FANS=1
# Disable the virtual temperature sensor for thermal team to tune the fan tbale
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=n
CONFIG_PLATFORM_EC_FAN_RPM_CUSTOM=n

# Charger
CONFIG_PLATFORM_EC_CHARGER_ISL9241=n
# RAA489108 register is the same as the ISL9238C
CONFIG_PLATFORM_EC_CHARGER_ISL9238C=y

# Keyboard
CONFIG_PLATFORM_EC_PWM_KBLIGHT=y
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_KEYBOARD_SCANCODE_CALLBACK=y

# Third party change
CONFIG_THIRD_PARTY_CUSTOMIZED_DESIGN=y

# Project
CONFIG_CHIPSET_INTEL=y

# PECI
CONFIG_PECI=y
CONFIG_PLATFORM_EC_PECI_TJMAX=100

# PS2 mouse emulation
CONFIG_PLATFORM_EC_TOUCHPAD_CUSTOMIZED=y
CONFIG_PLATFORM_EC_8042_AUX=y

# PD
CONFIG_PD_CHIP_CCG8=y
CONFIG_PD_CCG8_EPR=y
CONFIG_PD_WAIT_STABLE_TIMER=150
CONFIG_PD_CCG8_CUSTOMIZE_BATT_MESSAGE=y
CONFIG_PD_USB_PID=0x002F
CONFIG_PD_CCG8_CYPD_POWER_STATE_G3_SUPPORT=n
CONFIG_PLATFORM_EC_PD_RESET_BEFORE_EC_REBOOT=y
CONFIG_PLATFORM_EC_PD_IGNORE_EXIT_RT_MODE=y

# PD Controllers
# TODO: Once PD controller support is stable we'll want to enable it on future
# platforms
#CONFIG_PLATFORM_EC_CONSOLE_CMD_TYPEC=n
CONFIG_PLATFORM_EC_USBC=n
CONFIG_USB_PDC_POWER_MGMT=n
CONFIG_USB_PD_ALTMODE_INTEL=n

# System
CONFIG_PLATFORM_EC_SYSTEM_JUMP_RW_SUPPORT=y
CONFIG_PLATFORM_EC_POWER_BUTTON_INIT_TIMEOUT=2
CONFIG_PWRSEQ_AP_BOOT_DELAY=9
CONFIG_SHORT_HIBERNATE_TIMER=7
CONFIG_ESPI_NPCX_VWIRE_ENABLE_SEND_CHECK=y
