/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef __CROS_EC_DIAGNOSTICS_LAPTOP_H
#define __CROS_EC_DIAGNOSTICS_LAPTOP_H

enum diagnostics_device_idx {
	DIAGNOSTICS_START = 0,
	DIAGNOSTICS_HW_NO_BATTERY,
	DIAGNOSTICS_HW_PGOOD_3V5V,
	DIAGNOSTICS_VCCIN_AUX_VR,
	DIAGNOSTICS_SLP_S4,
	DIAGNOSTICS_HW_PGOOD_VR,

#ifdef CONFIG_BOARD_LOTUS
	DIAGNOSTICS_INPUT_MODULE_FAULT,
	DIAGNOSTICS_NO_LEFT_FAN,
	DIAGNOSTICS_NO_RIGHT_FAN,
	DIAGNOSTICS_GPU_MODULE_FAULT,
#else
	DIAGNOSTICS_TOUCHPAD,
	DIAGNOSTICS_AUDIO_DAUGHTERBOARD,
	DIAGNOSTICS_THERMAL_SENSOR,
	DIAGNOSTICS_NOFAN,
#endif
	DIAGNOSTICS_NO_S0,
	DIAGNOSTICS_NO_DDR,
	DIAGNOSTICS_NO_EDP,
	DIAGNOSTICS_HW_FINISH,

	/*BIOS BITS*/
	DIAGNOSTICS_BIOS_BIT0,
	DIAGNOSTICS_BIOS_BIT1,
	DIAGNOSTICS_BIOS_BIT2,
	DIAGNOSTICS_BIOS_BIT3,
	DIAGNOSTICS_BIOS_BIT4,
	DIAGNOSTICS_BIOS_BIT5,
	DIAGNOSTICS_BIOS_BIT6,
	DIAGNOSTICS_BIOS_BIT7,
	DIAGNOSTICS_MAX
};

void set_standalone_mode(int enable);

int get_standalone_mode(void);

bool diagnostics_tick(void);

#endif	/* __CROS_EC_DIAGNOSTICS_H */
