/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef __CROS_EC_DIAGNOSTICS_MINIPC_H
#define __CROS_EC_DIAGNOSTICS_MINIPC_H

enum diagnostics_device_idx {
	DIAGNOSTICS_START = 0,
	DIAGNOSTICS_PSU_POK,
	DIAGNOSTICS_12V_OK,
	DIAGNOSTICS_SLP_S5,
	DIAGNOSTICS_SLP_S4,
	DIAGNOSTICS_HW_PGOOD_VR,
	DIAGNOSTICS_NOFAN,
	DIAGNOSTICS_THERMAL_SENSOR,
	DIAGNOSTICS_NO_S0,
	DIAGNOSTICS_NO_DDR,
	DIAGNOSTICS_POWER_GLITCH,
	DIAGNOSTICS_HW_FINISH,

	/*BIOS BITS*/
	DIAGNOSTICS_BIOS_BIT0,
	DIAGNOSTICS_BIOS_BIT1,
	DIAGNOSTICS_BIOS_BIT2,
	DIAGNOSTICS_BIOS_BIT3,
	DIAGNOSTICS_BIOS_BIT4,
	DIAGNOSTICS_BIOS_BIT5,
	DIAGNOSTICS_BIOS_BIT6,
	DIAGNOSTICS_BIOS_BIT7,
	DIAGNOSTICS_BIOS_BIT8,
	DIAGNOSTICS_BIOS_BIT9,
	DIAGNOSTICS_BIOS_BIT10,
	DIAGNOSTICS_BIOS_BIT11,
	DIAGNOSTICS_BIOS_BIT12,
	DIAGNOSTICS_BIOS_BIT13,
	DIAGNOSTICS_BIOS_BIT14,
	DIAGNOSTICS_BIOS_BIT15,
	DIAGNOSTICS_MAX
};

#endif	/* __CROS_EC_DIAGNOSTICS_H */
