# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_TASK_CHIPSET_STACK_SIZE=1440

CONFIG_PM_DEVICE_RUNTIME=n
