# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_YAVIKS=y

# Save some firmware space
CONFIG_PLATFORM_EC_CONSOLE_CMD_MEM=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_I2C_PORTMAP=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_USB_PD_CABLE=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_APTHROTTLE=n

# FW image
# TODO: Once this configuration is configured with binman's size property
# by default, it can be removed.
CONFIG_CROS_EC_RW_SIZE=0x50000

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y

# Sensors: disabled; yaviks is clamshell-only
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=y
CONFIG_PLATFORM_EC_KBLIGHT_ENABLE_PIN=n
CONFIG_PLATFORM_EC_KEYBOARD_FACTORY_TEST=y

# Fan
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=y

# LED
CONFIG_PLATFORM_EC_LED_PWM=n

CONFIG_NISSA_SUB_BOARD=n

CONFIG_PLATFORM_EC_CMD_POWERINDEBUG=n

# Both ports use a SLGC55545 smart switch with CTL1..3 fixed high,
# for SDP2 or CDP only.
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_CDP_SDP_ONLY=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_DEFAULT_CDP=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_INVERTED=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_INPUT_CURRENT_DERATE_PCT=0
