/* Copyright 2022 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef __BOARD_CUSTOMIZED_SHARED_MEMORY_H
#define __BOARD_CUSTOMIZED_SHARED_MEMORY_H

/* Customized memmap start at offset 0x984 */
#define EC_CUSTOMIZED_MEMMAP_SYSTEM_FLAGS	0x84
#define EC_CUSTOMIZED_MEMMAP_POWER_STATE	0x85
#define EC_CUSTOMIZED_MEMMAP_WAKE_EVENT		0x86


/* Battery */
#define EC_CUSTOMIZED_MEMMAP_BATT_AVER_TEMP	0x87
#define EC_CUSTOMIZED_MEMMAP_BATT_CHARGE_CURR	0x88 /* Reserved */
#define EC_CUSTOMIZED_MEMMAP_BATT_PERCENTAGE	0x8A
#define EC_CUSTOMIZED_MEMMAP_BATT_STATUS	0x8B
#define EC_CUSTOMIZED_MEMMAP_BATT_TRIP_POINT	0x8C
#define EC_CUSTOMIZED_MEMMAP_BATT_MANUF_DAY	0xC1 /* Manufacturer date - day */
#define EC_CUSTOMIZED_MEMMAP_BATT_MANUF_MONTH	0xC2 /* Manufacturer date - month */
#define EC_CUSTOMIZED_MEMMAP_BATT_MANUF_YEAR	0xC3 /* Manufacturer date - year */

#define EC_BATT_FLAG_FULL			BIT(0) /* Full Charged */
#define EC_BATT_TYPE				BIT(1) /* (0: NiMh,1: LION) */
#define EC_BATT_MODE				BIT(2) /* (0=mW, 1=mA) */

#define EC_CUSTOMIZED_MEMMAP_DPTF_EVENT		0x90 /* Reserved */
#define EC_CUSTOMIZED_MEMMAP_PROJECTID		0x91 /* Reserved */

/* UCSI */
#define EC_CUSTOMIZED_MEMMAP_UCSI_VERSION	0x92
#define EC_CUSTOMIZED_MEMMAP_UCSI_CONN_CHANGE	0x94
#define EC_CUSTOMIZED_MEMMAP_UCSI_DATA_LEN	0x95
#define EC_CUSTOMIZED_MEMMAP_UCSI_RESERVE	0x96
#define EC_CUSTOMIZED_MEMMAP_UCSI_CCI		0x97
#define EC_CUSTOMIZED_MEMMAP_UCSI_COMMAND	0x98
#define EC_CUSTOMIZED_MEMMAP_UCSI_CTR_DATA_LEN	0x99
#define EC_CUSTOMIZED_MEMMAP_UCSI_CTR_SPECIFIC	0x9A
#define EC_CUSTOMIZED_MEMMAP_UCSI_MESSAGE_IN	0xA0
#define EC_CUSTOMIZED_MEMMAP_UCSI_MESSAGE_OUT	0xB0


#define EC_CUSTOMIZED_MEMMAP_SERIAL_STRCUT_INFO	0xC0
#define EC_CUSTOMIZED_MEMMAP_BIOS_SETUP_FUNC	0xC5
#define EC_CUSTOMIZED_MEMMAP_PD_VERSION		0xC6

#endif /* __BOARD_CUSTOMIZED_SHARED_MEMORY_H */
