# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_PTLRVP_MCHP=y
CONFIG_CROS_SYSTEM_XEC=y

CONFIG_MCHP_MEC_UNSIGNED_HEADER=y
CONFIG_MCHP_MEC_HEADER_FLASH_SIZE_256K=y

# For MCHP ESPI Drivers
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y
CONFIG_ESPI_PERIPHERAL_XEC_EMI0=y
CONFIG_ESPI_PERIPHERAL_ACPI_EC_IBF_EVT_DATA=y
CONFIG_ESPI_PERIPHERAL_KBC_OBE_CBK=y
CONFIG_ESPI_PERIPHERAL_KBC_IBF_EVT_DATA=y

CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y

# Keyboard
CONFIG_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_ITE_IT8801_KBD=y
CONFIG_CROS_EC_KEYBOARD_INPUT=y
CONFIG_PLATFORM_EC_KEYBOARD=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=13
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_8042=y
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y

# Enable tablet mode
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y

# Disable WDT for debugging
# TODO: remove when b/394349276 is resolved
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_CRYPTO=y

# Microchip internal WP gpio
CONFIG_CROS_FLASH_MCHP_INTERNAL_WP=y

# Enable PDC FW Update
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y

# Enable accessing IMVP
CONFIG_IMVP_RT3645_CONSOLE=y

# PPM Debug
CONFIG_UCSI_PPM_CONSOLE=y

# PDC Configuration
CONFIG_PDC_RUNTIME_PORT_CONFIG=y

# Reduce Flash Usage
CONFIG_PLATFORM_EC_HOSTCMD_THREAD_INFO=n
CONFIG_SHELL_TAB=n
