# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-npcx board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_NPCX=y

CONFIG_PLATFORM_EC_HIBERNATE_PSL=y

CONFIG_COMMON_BOARD_ID=y

CONFIG_PLATFORM_EC_USBC_RETIMER_FW_UPDATE=y
