# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Uldrenite reference-board-specific Kconfig settings.
CONFIG_BOARD_ULDRENITE=y

# CBI
CONFIG_PLATFORM_EC_CBI_TRANSFER_EEPROM_FLASH=y
CONFIG_EEPROM=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y
CONFIG_PLATFORM_EC_EEPROM_CBI_WP=y

# Keyboard
CONFIG_PLATFORM_EC_KBLIGHT_ENABLE_PIN=n
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18

# Battery
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y

#Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE=y
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE_AP_ON=300000
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE_AP_OFF=500000

# Power
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=45000
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=15000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=3000

#Sensor
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
CONFIG_PLATFORM_EC_BODY_DETECTION_NOTIFY_MODE_CHANGE=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_ILIM_PIN_DISABLED=y

# IMVP9
CONFIG_PLATFORM_EC_PMIC=y

CONFIG_PDC_RUNTIME_PORT_CONFIG=y

# DSP
CONFIG_PLATFORM_EC_DSP_SERVICE=y
CONFIG_PLATFORM_EC_DSP_INIT_PRIORITY=80
CONFIG_PLATFORM_EC_DSP_REMOTE_BODY_DETECTION=y
CONFIG_PLATFORM_EC_DSP_REMOTE_CBI=y
CONFIG_PLATFORM_EC_DSP_REMOTE_LID_SWITCH=y
CONFIG_PLATFORM_EC_DSP_REMOTE_TABLET_SWITCH=y
CONFIG_PLATFORM_EC_DSP_REMOTE_LID_ANGLE=y
CONFIG_PLATFORM_EC_DSP_RESPONSE_BUFFER_SIZE=128
CONFIG_I2C_TARGET=y

# b/445058814
CONFIG_PLATFORM_EC_DEBUG_ASSERT=n
