# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-rts board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_RTK=y

# eSPI
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

# Disable options not yet configured
CONFIG_NAMED_ADC_CHANNELS=n
CONFIG_PWM=n
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_UCSI_PPM=n
CONFIG_PLATFORM_EC_MKBP_EVENT=n
CONFIG_PLATFORM_EC_MKBP_INPUT_DEVICES=n
CONFIG_PLATFORM_EC_MKBP_USE_GPIO_AND_HOST_EVENT=n
