# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# mensa board-specific Kconfig settings.

CONFIG_BOARD_MENSA=y

# External Power
CONFIG_PLATFORM_EC_EXTPOWER_GPIO_CUSTOM=y
