# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# matsu board-specific Kconfig settings.

CONFIG_BOARD_MATSU=y

CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y

# AP to EC communication
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S3=n
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S4=n
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S5=y
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y
CONFIG_HCDEBUG_OFF=y

# Lid
CONFIG_PLATFORM_EC_BACKLIGHT_LID=y

# EFS2
CONFIG_PLATFORM_EC_VBOOT_EFS2=y

# Disable options not yet configured
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y

# PDC
CONFIG_PDC_RUNTIME_PORT_CONFIG=n
CONFIG_USBC_PDC_TPS6699X_CONSOLE_FW_UPDATER=n
CONFIG_PLATFORM_EC_USB_PD_MAX_VOLTAGE_MV=20000
CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=65000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=3250

# Bring up configs
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y
