# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ET171=y

CONFIG_PLATFORM_EC_NOINIT_END_OF_RAM_SECTION=n
CONFIG_PLATFORM_EC_FLASH_SIZE_BYTES=200000
CONFIG_XIP=y

CONFIG_EXCEPTION_DEBUG=y
CONFIG_PLATFORM_EC_ROLLBACK_MPU_PROTECT=y

# Watchdog related configs
# Maximum watchdog period for atcwdt200 is 500ms. Many operations in the FP
# application takes hundreds of milliseconds or even more, e.g. RWSIG, flash
# operations, FP related calculations. Combining such two actions in series
# would lead to watchdog reset, thus we are forced to disable watchdog.
CONFIG_WDT_DISABLE_AT_BOOT=y
# The tick hook is used only for watchdog reload for FPMCU
CONFIG_PLATFORM_EC_HOOK_TICK=n

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# 2kB looks sufficient, but add additional margin for future changes
CONFIG_UDC_BUF_POOL_SIZE=3072
CONFIG_USBD_THREAD_STACK_SIZE=2048
CONFIG_USB_DEVICE_MAX_POWER=250

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"
CONFIG_USB_DEVICE_SN_HWINFO=y

# Use USB for signaling MKBP events
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_USB=y

# Sizes adjusted for 512 bytes payload for write and read flash host commands
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520

CONFIG_FPU_SHARING=n
CONFIG_FLOAT_HARD=y

# SPI/Flash related configs
CONFIG_SPI_NOR=n
CONFIG_FLASH_ANDES_QSPI=n
CONFIG_FLASH_ANDES_QSPI_XIP_COUNT_REGS=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

# BBRAM not supported on ET171, use RAM instead
CONFIG_BBRAM=n
CONFIG_RETAINED_MEM=y
CONFIG_RETAINED_MEM_INIT_PRIORITY=15
CONFIG_CACHE_ANDES_INIT_PRIORITY=10
CONFIG_RETAINED_MEM_MUTEX_FORCE_DISABLE=y

# Use standar 0.1ms tick
CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000

# No access to hardware WP pin, use external method
CONFIG_PLATFORM_EC_WP_EXTERNAL=y

# FPS related configs
CONFIG_FINGERPRINT_SENSOR_EGIS630_HEAP_SIZE=153600

# Enable the fp vendor command to get MT data
CONFIG_PLATFORM_EC_FINGERPRINT_VENDOR_COMMAND=y

# Make possibility to enter bootloader
CONFIG_PLATFORM_EC_HOST_COMMAND_ENTER_BOOTLOADER=y

# Disable kernel shell, becasue it requires addtional 5kB of flash
CONFIG_KERNEL_SHELL=n

# The flash shell requires page layout which is not supported
CONFIG_FLASH_SHELL=n

# Make sure to start shell before main
CONFIG_PLATFORM_EC_CONSOLE_START_SHELL_TASK=y

# RISCV PMP entry configurations
# b/406946889: Allow modifying PMP entries so that we can reconfigure them
# when jumping between RO and RW.
CONFIG_PMP_NO_LOCK_GLOBAL=y
CONFIG_NULL_POINTER_EXCEPTION_DETECTION_PMP=y
CONFIG_HW_STACK_PROTECTION=y

# Use EGIS ET171's secure OTP storage for keys.
CONFIG_EGIS_ET171_OTP_KEY=y

# Current rollback version value.
CONFIG_PLATFORM_EC_ROLLBACK_VERSION=1

# ASCP s_goog replacement
CONFIG_ASCP_S_GOOG_MATCH_FILE="s_goog_match.bin"
CONFIG_ASCP_S_GOOG_REPLACE_FILE="s_goog_replace.bin"

# Enable signaling logs via events to allow autosuspend
CONFIG_PLATFORM_EC_HOSTCMD_CONSOLE_EVENT=y
