# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_FT9001=y

# The NULL pointer exception page size must be a power of two
# and have size greater or equal ARM_MPU_REGION_MIN_ALIGN_AND_SIZE
CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE=0x80

# Peripherials
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_SPI_ASYNC=y
CONFIG_HWINFO=y
CONFIG_HWINFO_FOCALTECH=y

# Stack and rollback protection
CONFIG_ARM_MPU=y
CONFIG_HW_STACK_PROTECTION=y

# Do not use partition for code, because the code location is different for RO
# and RW
CONFIG_USE_DT_CODE_PARTITION=n

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# 2kB looks sufficient, but add additional margin for future changes
CONFIG_UDC_BUF_POOL_SIZE=3072
CONFIG_USBD_THREAD_STACK_SIZE=2048

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"
CONFIG_USB_DEVICE_SN_HWINFO=y
CONFIG_USB_DEVICE_MAX_POWER=250

# Use USB for signaling MKBP events
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_USB=y

# Sizes adjusted for 512 bytes payload for write and read flash host commands
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520

# BBRAM not supported on FT9001, use RAM instead
CONFIG_BBRAM=n
CONFIG_RETAINED_MEM=y
CONFIG_RETAINED_MEM_INIT_PRIORITY=15
CONFIG_RETAINED_MEM_MUTEX_FORCE_DISABLE=y

# Arch init for RO -> RW jump
CONFIG_INIT_ARCH_HW_AT_BOOT=y

# Make possibility to enter bootloader
CONFIG_PLATFORM_EC_HOST_COMMAND_ENTER_BOOTLOADER=y

# No access to hardware WP pin, use external method
CONFIG_PLATFORM_EC_WP_EXTERNAL=y

# Current rollback version value.
CONFIG_PLATFORM_EC_ROLLBACK_VERSION=1

# Make sure to start shell before main
CONFIG_PLATFORM_EC_CONSOLE_START_SHELL_TASK=y

# ASCP s_goog replacement
CONFIG_ASCP_S_GOOG_MATCH_FILE="s_goog_match.bin"
CONFIG_ASCP_S_GOOG_REPLACE_FILE="s_goog_replace.bin"

# Watchdog, 3000ms is the maximum time window at system clock 160M.
CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=3000

# Enable signaling logs via events to allow autosuspend
CONFIG_PLATFORM_EC_HOSTCMD_CONSOLE_EVENT=y

CONFIG_FOCALTECH_OTP_KEY=y
