/* Copyright 2016 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * Register map for Rotor MCU
 */

#ifndef __CROS_EC_REGISTERS_H
#define __CROS_EC_REGISTERS_H

#include "common.h"

/* Master clocks and resets. */
#define ROTOR_MCU_CLKRSTGEN_BASE	0xEF000800
#define ROTOR_MCU_RESETAP		REG32(ROTOR_MCU_CLKRSTGEN_BASE + 0x000)
#define ROTOR_MCU_AP_NRESET		(1 << 0)
#define ROTOR_MCU_M4_BIST_CLKCFG	REG32(ROTOR_MCU_CLKRSTGEN_BASE + 0x140)

/* GPIO */
#define DUMMY_GPIO_BANK 0

#define GPIO_A 0xEF022000
#define GPIO_B 0xEF022100
#define GPIO_C 0xEF022200
#define GPIO_D 0xEF022300
#define GPIO_E 0xEF022400

#define ROTOR_MCU_GPIO_PLR(b)		REG32((b) + 0x0)
#define ROTOR_MCU_GPIO_PDR(b)		REG32((b) + 0x4)
#define ROTOR_MCU_GPIO_PSR(b)		REG32((b) + 0xC)
#define ROTOR_MCU_GPIO_HRIPR(b)		REG32((b) + 0x10)
#define ROTOR_MCU_GPIO_LFIPR(b)		REG32((b) + 0x14)
#define ROTOR_MCU_GPIO_ISR(b)		REG32((b) + 0x18)
#define ROTOR_MCU_GPIO_SDR(b)		REG32((b) + 0x1C)
#define ROTOR_MCU_GPIO_CDR(b)		REG32((b) + 0x20)
#define ROTOR_MCU_GPIO_SHRIPR(b)	REG32((b) + 0x24)
#define ROTOR_MCU_GPIO_CHRIPR(b)	REG32((b) + 0x28)
#define ROTOR_MCU_GPIO_SLFIPR(b)	REG32((b) + 0x2C)
#define ROTOR_MCU_GPIO_CLFIPR(b)	REG32((b) + 0x30)
#define ROTOR_MCU_GPIO_OLR(b)		REG32((b) + 0x34)
#define ROTOR_MCU_GPIO_DWER(b)		REG32((b) + 0x38)
#define ROTOR_MCU_GPIO_IMR(b)		REG32((b) + 0x3C)
#define ROTOR_MCU_GPIO_SIMR(b)		REG32((b) + 0x48)
#define ROTOR_MCU_GPIO_CIMR(b)		REG32((b) + 0x4C)
/* Interrupt Target Enable regs for MCU are instances 24-31. */
#define ROTOR_MCU_GPIO_ITER(b)		REG32((b) + 0xB0 + \
					      4*(((b) - GPIO_A) >> 8))


/* MCU Pad Wrap */
#define ROTOR_MCU_PAD_WRAP_BASE	0xEF020000
#define ROTOR_MCU_IO_PAD_CFG(n)	REG32(ROTOR_MCU_PAD_WRAP_BASE + 0x8 + \
				      ((n) * 0x4))

#define GPIO_PAD_CFG_IDX(port, pin)	(((((port) % 0x2000) / 0x100) * 32) + \
					 (pin))
#define GPIO_PAD_CFG_ADDR(port, pin)	((GPIO_PAD_CFG_IDX(port, pin) * 4) + \
					 ROTOR_MCU_PAD_WRAP_BASE + 8)
#define ROTOR_MCU_GPIO_PCFG(port, pin)	REG32(GPIO_PAD_CFG_ADDR(port, pin))

/* I2C */
#define ROTOR_MCU_I2C_BASE		0xED080000
#define ROTOR_MCU_I2C_CFG_BASE(n)	(ROTOR_MCU_I2C_BASE + (n)*0x1000)
#define ROTOR_MCU_I2C_CON(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x00)
#define ROTOR_MCU_I2C_TAR(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x04)
#define ROTOR_MCU_I2C_SAR(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x08)
#define ROTOR_MCU_I2C_HS_MADDR(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x0C)
#define ROTOR_MCU_I2C_DATA_CMD(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x10)
#define ROTOR_MCU_I2C_SS_SCL_HCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x14)
#define ROTOR_MCU_I2C_SS_SCL_LCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x18)
#define ROTOR_MCU_I2C_FS_SCL_HCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x1C)
#define ROTOR_MCU_I2C_FS_SCL_LCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x20)
#define ROTOR_MCU_I2C_HS_SCL_HCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x24)
#define ROTOR_MCU_I2C_HS_SCL_LCNT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x28)
#define ROTOR_MCU_I2C_INTR_STAT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x2C)
#define ROTOR_MCU_I2C_INTR_MASK(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x30)
#define ROTOR_MCU_I2C_RAW_INTR_STAT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x34)
#define ROTOR_MCU_I2C_RX_TL(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x38)
#define ROTOR_MCU_I2C_TX_TL(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x3C)
#define ROTOR_MCU_I2C_CLR_INTR(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x40)
#define ROTOR_MCU_I2C_CLR_RX_UNDER(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x44)
#define ROTOR_MCU_I2C_CLR_RX_OVER(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x48)
#define ROTOR_MCU_I2C_CLR_TX_OVER(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x4C)
#define ROTOR_MCU_I2C_CLR_RD_REQ(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x50)
#define ROTOR_MCU_I2C_CLR_TX_ABRT(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x54)
#define ROTOR_MCU_I2C_CLR_RX_DONE(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x58)
#define ROTOR_MCU_I2C_CLR_ACTIVITY(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x5C)
#define ROTOR_MCU_I2C_CLR_STOP_DET(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x60)
#define ROTOR_MCU_I2C_CLR_START_DET(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x64)
#define ROTOR_MCU_I2C_CLR_GEN_CALL(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x68)
#define ROTOR_MCU_I2C_ENABLE(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x6C)
#define ROTOR_MCU_I2C_STATUS(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x70)
#define ROTOR_MCU_I2C_TXFLR(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x74)
#define ROTOR_MCU_I2C_RXFLR(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x78)
#define ROTOR_MCU_I2C_SDA_HOLD(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x7C)
#define ROTOR_MCU_I2C_TX_ABRT_SRC(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x80)
#define ROTOR_MCU_I2C_DMA_CR(n)		REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x88)
#define ROTOR_MCU_I2C_DMA_TDLR(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x8C)
#define ROTOR_MCU_I2C_DMA_RDLR(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x90)
#define ROTOR_MCU_I2C_SDA_SETUP(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x94)
#define ROTOR_MCU_I2C_ACK_GEN_CALL(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x98)
#define ROTOR_MCU_I2C_ENABLE_STATUS(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0x9C)
#define ROTOR_MCU_I2C_FS_SPKLEN(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0xA0)
#define ROTOR_MCU_I2C_HS_SPKLEN(n)	REG32(ROTOR_MCU_I2C_CFG_BASE(n) + 0xA4)
#define ROTOR_MCU_I2C_REFCLKGEN(n)	REG32((ROTOR_MCU_CLKRSTGEN_BASE + \
					       + 0x3D0 + (0x10 * (n))))

/* UART */
#define ROTOR_MCU_UART0_CLKGEN		REG32(ROTOR_MCU_CLKRSTGEN_BASE + 0x240)
#define ROTOR_MCU_UART0_REFCLKGEN	REG32(ROTOR_MCU_CLKRSTGEN_BASE + 0x3B0)
#define ROTOR_MCU_UART_CFG_BASE(n)	(0xED060000 + (n)*0x1000)
/* DLAB = 0 */
#define ROTOR_MCU_UART_RBR(n) /* R */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x0)
#define ROTOR_MCU_UART_THR(n) /* W */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x0)
#define ROTOR_MCU_UART_IER(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x4)
/* DLAB = 1 */
#define ROTOR_MCU_UART_DLL(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x0)
#define ROTOR_MCU_UART_DLH(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x4)

#define ROTOR_MCU_UART_IIR(n) /* R */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x8)
#define ROTOR_MCU_UART_FCR(n) /* W */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x8)
#define ROTOR_MCU_UART_LCR(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0xC)
#define ROTOR_MCU_UART_MCR(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x10)
#define ROTOR_MCU_UART_LSR(n) /* R */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x14)
#define ROTOR_MCU_UART_MSR(n) /* R */	REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x18)
#define ROTOR_MCU_UART_SCR(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x1C)
#define ROTOR_MCU_UART_USR(n)		REG32(ROTOR_MCU_UART_CFG_BASE(n) + 0x7C)

/* Timers */
#define ROTOR_MCU_TMR_CFG_BASE(n)	(0xED020000 + (n)*0x1000)
#define ROTOR_MCU_TMR_TNLC(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0x0)
#define ROTOR_MCU_TMR_TNCV(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0x4)
#define ROTOR_MCU_TMR_TNCR(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0x8)
#define ROTOR_MCU_TMR_TNEOI(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0xC)
#define ROTOR_MCU_TMR_TNIS(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0x10)
#define ROTOR_MCU_TMR_TIS(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0xA0)
#define ROTOR_MCU_TMR_TEOI(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0xA4)
#define ROTOR_MCU_TMR_TRIS(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0xA8)
#define ROTOR_MCU_TMR_TNLC2(n)		REG32(ROTOR_MCU_TMR_CFG_BASE(n) + 0xB0)

/* Watchdog */
#define ROTOR_MCU_WDT_BASE		0xED010000
#define ROTOR_MCU_WDT_CR		REG32(ROTOR_MCU_WDT_BASE + 0x00)
#define ROTOR_MCU_WDT_TORR		REG32(ROTOR_MCU_WDT_BASE + 0x04)
#define ROTOR_MCU_WDT_CCVR		REG32(ROTOR_MCU_WDT_BASE + 0x08)
#define ROTOR_MCU_WDT_CRR		REG32(ROTOR_MCU_WDT_BASE + 0x0C)
#define ROTOR_MCU_WDT_STAT		REG32(ROTOR_MCU_WDT_BASE + 0x10)
#define ROTOR_MCU_WDT_EOI		REG32(ROTOR_MCU_WDT_BASE + 0x14)
/* To prevent accidental restarts, this magic value must be written to CRR. */
#define ROTOR_MCU_WDT_KICK		0x76

/* IRQ Numbers */
#define ROTOR_MCU_IRQ_TIMER_0		6
#define ROTOR_MCU_IRQ_TIMER_1		7
#define ROTOR_MCU_IRQ_WDT		14
#define ROTOR_MCU_IRQ_UART_0		16
#define ROTOR_MCU_IRQ_GPIO_0		79
#define ROTOR_MCU_IRQ_GPIO_1		80
#define ROTOR_MCU_IRQ_GPIO_2		81
#define ROTOR_MCU_IRQ_GPIO_3		82
#define ROTOR_MCU_IRQ_GPIO_4		83
#define ROTOR_MCU_IRQ_GPIO_5		84
#define ROTOR_MCU_IRQ_GPIO_6		85
#define ROTOR_MCU_IRQ_GPIO_7		86

#endif /* __CROS_EC_REGISTERS_H */
