/* Copyright 2021 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CHARGER_INTERSIL_ISL9241_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CHARGER_INTERSIL_ISL9241_H_

#define SWITCHING_FREQ_1420KHZ 0
#define SWITCHING_FREQ_1180KHZ 1
#define SWITCHING_FREQ_1020KHZ 2
#define SWITCHING_FREQ_890KHZ  3
#define SWITCHING_FREQ_808KHZ  4
#define SWITCHING_FREQ_724KHZ  5
#define SWITCHING_FREQ_656KHZ  6
#define SWITCHING_FREQ_600KHZ  7

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CHARGER_INTERSIL_ISL9241_H_ */
