# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_EM32F967=y

# The NULL pointer exception page size must be a power of two
# and have size greater or equal ARM_MPU_REGION_MIN_ALIGN_AND_SIZE
CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE=0x80

# Peripherials
CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_PINCTRL=y
CONFIG_FLASH_EM32=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_EM32=y
CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_EM32_AHB=y
CONFIG_CLOCK_CONTROL_EM32_APB=y
CONFIG_DYNAMIC_INTERRUPTS=y

# Stack and rollback protection
CONFIG_ARM_MPU=y
CONFIG_HW_STACK_PROTECTION=y

# USB for host commands
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_BUF_POOL_SIZE=2048
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520

# Watchdog
CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=10000
CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=3000

# MKBP
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_USB=y

# Arch init for RO -> RW jump
CONFIG_INIT_ARCH_HW_AT_BOOT=y

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0x5405
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"
CONFIG_USB_DEVICE_SN_HWINFO=y
CONFIG_USB_DEVICE_MAX_POWER=250

# Make possibility to enter bootloader
CONFIG_PLATFORM_EC_HOST_COMMAND_ENTER_BOOTLOADER=y

# No access to hardware WP pin, use custom method
CONFIG_PLATFORM_EC_WP_CUSTOM=y

# TODO(b/479094824): Leave printk until firmware is fully developed.
CONFIG_LOG_PRINTK=n

# TODO(b/450715297): Enable power saving mode once supported
CONFIG_PM=n
CONFIG_PM_DEVICE=n
