# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_VADER=y

# Bring up options
CONFIG_PLATFORM_EC_BRINGUP=n
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=n

# motionsense
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCEL_BMA4XX=y
CONFIG_PLATFORM_EC_LID_ANGLE=y
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=y
CONFIG_PLATFORM_EC_DYNAMIC_MOTION_SENSOR_COUNT=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=n
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y

# PDC
CONFIG_PDC_RUNTIME_PORT_CONFIG=y
CONFIG_USBC_PDC_RTS54XX_CONSOLE_FW_UPDATER=y

# Button
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE=y
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE_AP_ON=300000
CONFIG_PLATFORM_EC_POWER_BUTTON_DEBOUNCE_AP_OFF=500000
