name: build lotus, azalea firmware

on:
  push:
    branches:
      - fwk-*
      - pr-*

jobs:
  build:
    name: Build lotus/azalea
    runs-on: [marigold-builders]

    strategy:
      # Only build one at a time because we have only one working directory
      max-parallel: 1
      matrix:
        platform: [
          # c1488028cf525335b95b277112795219dc6b7688 is bad and won't build with our lotus EC branch
          { name: lotus, folder: marigold1, ver: "0.0.0", sha_len: 7, zephyr_ref: "lotus-zephyr", cmsis_ref: "c1488028cf525335b95b277112795219dc6b7688^", remote: "github-private" },
          { name: azalea, folder: marigold1, ver: "0.0.0", sha_len: 7, zephyr_ref: "lotus-zephyr", cmsis_ref: "c1488028cf525335b95b277112795219dc6b7688^", remote: "github-private" },
        ]


    # Build not in $GITHUB_HOME but in the chroot env
    defaults:
      run:
        working-directory: /${{ matrix.platform.folder }}/ec_home/chromiumos

    steps:
      # Need to use git
      #- name: Checkout EC code
      #  uses: actions/checkout@v4
      #  with:
      #    path: /lotus/ec_home/chromiumos/src/platform/ec

      #- name: Checkout Zephyr code
      #  uses: actions/checkout@v2
      #    path: /lotus/ec_home/chromiumos/src/third_party/zephyr/main
      #    ref: lotus-zephyr
      #    repository: ssh://git@github.com/FrameworkComputer/zephyr-ec

      # Need to manually checkout
      # actions/checkout@v4 complains:
      # Error: Repository path '/lotus/ec_home/chromiumos/src/platform/ec' is not under '/data/ec_home/actions-runner/_work/ec/ec'
      # See: https://github.com/actions/checkout/issues/197
      - name: Manual checkout
        run: |
          pushd src/platform/ec
          git fetch ${{ matrix.platform.remote }}
          git clean -ffdx
          # TODO: Doesn't work with on PR, only push
          git reset --hard ${{ matrix.platform.remote }}/$GITHUB_REF_NAME
          popd

          pushd src/third_party/zephyr/main
          git fetch ${{ matrix.platform.remote }}
          git clean -ffdx
          git reset --hard ${{ matrix.platform.remote }}/${{ matrix.platform.zephyr_ref }}
          popd

          pushd src/third_party/zephyr/cmsis
          git fetch cros
          git clean -ffdx
          git reset --hard ${{ matrix.platform.cmsis_ref }}
          popd

      - name: Build ${{ matrix.platform.name }}
        run: |
          cros_sdk zmake build ${{ matrix.platform.name }}
          echo Built ${{ matrix.platform.name }} EC

      - name: File sha256
        run: sha256sum src/platform/ec/build/zephyr/${{ matrix.platform.name }}/output/ec.bin

      - name: Generate artifact version
        run: |
          echo "VERSIONINFO=$(date -u +'%Y-%m-%d-%H-%M-%S')_$GITHUB_SHA" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}.${{ env.VERSIONINFO }}
          path: /${{ matrix.platform.folder }}/ec_home/chromiumos/src/platform/ec/build/zephyr/${{ matrix.platform.name }}/output
