name: Build Framework Zephyr EC firmware

on:
  create:
  push:
    branches:
      - marigold*
      - lotus*
      - azalea*
      - fwk*
      - framework*
  #  paths:
  #    - 'zephyr/program/framework/**'
  #pull_request:
  #  branches:
  #    - marigold
  # Dispatch only works on the main branch, so we can't actually use it here
  workflow_dispatch:

jobs:
  build:
    runs-on: [marigold-builders]

    strategy:
      # Only build one at a time because we have only one working directory
      max-parallel: 1
      matrix:
        platform: [
          # Marigold builder uses same folder for all
          { name: marigold, folder: marigold1, ver: "1.0.0" },
          { name: lotus, folder: marigold1, ver: "3.0.3" },
          { name: azalea, folder: marigold1, ver: "3.0.5" },
        ]


    # Build not in $GITHUB_HOME but in the chroot env
    defaults:
      run:
        working-directory: /${{ matrix.platform.folder }}/ec_home/chromiumos

    steps:
      # Need to use git
      #- name: Checkout EC code
      #  uses: actions/checkout@v4
      #  with:
      #    path: /${{ matrix.platform.folder }}/ec_home/chromiumos/src/platform/ec

      #- name: Checkout Zephyr code
      #  uses: actions/checkout@v2
      #    path: /${{ matrix.platform.folder }}/ec_home/chromiumos/src/third_party/zephyr/main
      #    ref: lotus-zephyr
      #    repository: ssh://git@github.com/FrameworkComputer/zephyr-ec

      # Need to manually checkout
      # actions/checkout@v4 complains:
      # Error: Repository path '/data/ec_home/chromiumos/src/platform/ec' is not under '/data/ec_home/actions-runner/_work/ec/ec'
      # See: https://github.com/actions/checkout/issues/197
      - name: Manual checkout
        run: |
          pushd src/platform/ec
          git fetch github-private
          git clean -ffdx
          # TODO: Doesn't work with on PR, only push
          git reset --hard github-private/$GITHUB_REF_NAME
          popd

          pushd src/third_party/zephyr/main
          git fetch github-private
          git clean -ffdx
          # Previous one is: ee0cd57778e00c49269068d049a4b7e237500134
          # New one is:      b3843c543ca1d8d4811fd7f7e37484b19207c54b
          git reset --hard github-private/marigold.upstream-merge
          popd

      # Note:
      # By default cros_sdk changes into src/scripts folder.
      # But that will make zmake pick up the scripts git commit SHA
      # To embed the ec repo's commit SHA we need to change pwd there
      - name: Build ${{ matrix.platform.name }}
        run: cros_sdk bash -c 'pushd ../platform/ec; zmake -D build -v ${{ matrix.platform.ver }} ${{ matrix.platform.name }}'

      - name: File sha256
        run: sha256sum src/platform/ec/build/zephyr/${{ matrix.platform.name }}/output/ec.bin

      - name: Check version embedded in binary
        run: |
          strings src/platform/ec/build/zephyr/${{ matrix.platform.name }}/output/ec.bin | grep ${{ matrix.platform.name }} | tee bin-strings.txt
          grep $(echo "$GITHUB_SHA" | cut -c1-7) bin-strings.txt

      - name: Generate artifact version
        run: |
          echo "VERSIONINFO=$(date -u +'%Y-%m-%d-%H-%M-%S')_$GITHUB_SHA" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}.${{ env.VERSIONINFO }}
          path: /${{ matrix.platform.folder }}/ec_home/chromiumos/src/platform/ec/build/zephyr/${{ matrix.platform.name }}/output
