# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


# Project
CONFIG_BOARD_DOGWOOD=y
CONFIG_CHIPSET_AMD=y
CONFIG_PLATFORM_SIMPLE_VERSION_SHIFT_IDX=14


# Host interface
CONFIG_ESPI_VWIRE_INDEX_33H=y
CONFIG_PLATFORM_EC_AMD_SB_RMI=y
CONFIG_PLATFORM_EC_SCI_GPIO=y

# Fan (TODO: add the third fan)
CONFIG_PLATFORM_EC_NUM_FANS=2

# PD
CONFIG_PLATFORM_EC_PD_CHIP_MAX_COUNT=1
CONFIG_PD_CHIP_CCG6=y
CONFIG_PLATFORM_EC_USBC=n
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
CONFIG_PLATFORM_EC_USB_PD_DISCHARGE=n
CONFIG_PD_CCG6_EC_UART_DEBUG_PORT=1
CONFIG_PD_CCG6_SOC_UART_DEBUG_PORT=0

# Thermal
CONFIG_PLATFORM_EC_TEMP_SENSOR_F75303=y
CONFIG_PLATFORM_EC_TEMP_SENSOR_SB_TSI=y

# INA2XX
CONFIG_PLATFORM_EC_INA2XX=y
CONFIG_PLATFORM_EC_INA236=y

# System
CONFIG_PLATFORM_EC_SYSTEM_JUMP_RW_SUPPORT=y
